### ISSUE TITLE
Reasoner: Process IVML eval

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#14]
Process all evals inside-out before processing the project contents

**Comment by eichelbe** [comment]
See also related [issue 58](https://github.com/QualiMaster/QM-IConf/issues/58) in QM-ICon

**Comment by rsizonenko** [comment]
Main project constraints in eval block are processed as a priority. Needs more testing on specific scenarios.

**Comment by rsizonenko** [comment]
Compound eval support added. Nested eval blocks both in main model and compound are supported.
