### ISSUE TITLE
Reasoner: Undefined variables in if statements are not handled correctly

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#15]
A. Krafczy: 

This model

```
enum UnitSystem {metric, imperial};
enum Country {usa, germany, china};

UnitSystem system;
Country country;

if country == Country.usa
    then system == UnitSystem.imperial
    else system == UnitSystem.metric
endif;

system = UnitSystem.imperial;
country = Country.usa;
```

fails, although it shouldn't. The if is evaluated first and since country is undefined it jumps into the else part, which leads to an automatic assignment and conflicts with the assignemt below. The if shouldn't be evaluated if country is undefined.

A test case for this is in de.uni_hildesheim.sse.reasoning.reasoner.StressTest.testIfWithUndefinedValues()

**Comment by rsizonenko** [comment]
Reasoner seems to be handling this case correctly. Could not reproduce the bug.
