### ISSUE TITLE
Reasoner: Typedef constraints are not considered in sequences / sets

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#16]
A. Krafczy

This model

```
typedef PosInteger Integer with (PosInteger >= 0);
sequenceOf(PosInteger) seq;
seq = {5, -3};
```

does not produce an error, although -3 is clearly not >= 0.

A test case for this is in de.uni_hildesheim.sse.reasoning.reasoner.StressTest.testTypedefConstraintsInSequences()

**Comment by rsizonenko** [comment]
Solved

**Comment by Elscha** [comment]
Now it is not longer possible to use an alias inside a compound.
Created test case in ReasonerCore.tests -> AliasUsedInSet.ivml

**Comment by rsizonenko** [comment]
Fixed this + foreach loop optimized
