### ISSUE TITLE
Product line editor reverses order of projects in the same file

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#27]
A. Krafczy:
Consider the following situation:

project PL_Test01 {
    version v0;
    Integer a;
    a = 5;
}
project Other {
    version v0;
    import PL_Test01;
    PL_Test01::a = 2;
}

When configuring PL_Test01 with the product line editor and saving the changes, the file is written like this:

project Other {
    version v0;
    import PL_Test01;
    a = 2;
}
project PL_Test01 {
    version v0;
    Integer a;
    a = 3;
}

The order of the projects is changed, which leads to problems when resolving the import, and the prefix for "a" is removed in "Other".

Note that the other way round (i.e. "PL_Test01" importing "Other") everything works fine. Also it seems that it's ordered alphabetically.

**Comment by Elscha** [comment]
This should already be fixed, cannot reproduce this.
