### ISSUE TITLE
Reasoner finds too many projects for cyclic imports

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#28]
A. Krafczy:

project MainProject {
    import Project1;

```
a = 1;
```

}
project Project1 {
    import Project2;

```
Integer a;
a > 2;
```

}
project Project2 {
    import Project1;
}

Running the reasoner on these projects causes too many error messages. This is because Resolver.findImportedProjects() finds Project1 and Project2 more than once.

Resolver.findImportedProjects() uses a Set<Project> to keep track of already found projects, but this doesn't work, since it seems that ProjectImport.getResolved() returns different instances (i.e. different Java objects) for the same projects.

For testing purposes, I added a custom equals() method to ModelElement, that compares the qualified name. This almost fixes the problem; Project2 is found only 1 time but Project1 is found 2 times. This indicates that there may be another issue, apart from the different objects for the same project.

**Comment by eichelbe** [comment]
Sascha added an initial test case...

**Comment by eichelbe** [comment]
Is this still the case -> test case? If yes, assign to Roman. May cause performance issues.

**Comment by Elscha** [comment]
Seems to work.
Current **list** of projects is: `[Project1, Project2, PL_Main]`
Current error dialog shows the following message:
![reasonermessage](https://cloud.githubusercontent.com/assets/6489033/14012575/e4eea1d8-f1a6-11e5-9c2e-8e00b5cdc13c.png)

However, the ReasonerModel of ReasonerCore, which is used by Drools2-Reasoner, produces a StackOverflowException. It seems that the "general" ReasonerModel is only used by Drools2. -> Mode/Remove this model?

**Comment by eichelbe** [comment]
As far as I remember, we decided to move Drools2 to Obsolete. Then I would also move the model there as it is not needed anymore.

**Comment by rsizonenko** [comment]
ReasonerModel is only used by Drools2. So it would be safe just to take it out of the current implementation.

**Comment by Elscha** [comment]
@rsizonenko: Please clean up ReasonerCore through moving drools specific code from ReasonerCore to Drools. Please notify me if you are done.

**Comment by rsizonenko** [comment]
ReasonerModel relocated to Drools2
