### ISSUE TITLE
Upgrade xText

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#3]
Switch to the most recent version of xText.
State: 
- generation works
- tests are passing
- change of bundles during generation by new xText version are under analysis

Blocks #2

**Comment by ckroeher** [comment]
<b>Regarding issue:</b>

<ul><li>change of bundles during generation by new xText version are under analysis</li></ul>

<b>Status: solved</b><br>
<b>Explanation:</b>
The issue arises from warnings produced while generating the VIL and VTL languages, like:<br>
<i>304  [main] WARN  lipse.emf.mwe.utils.StandaloneSetup  - Skipping conflicting project org.apache.commons.io at 'archive:file:/C:/Kroeher/Downloads/Eclipse%20SSE/plugins/org.apache.commons.io_2.4.0.jar!/' and using 'archive:file:/C:/Kroeher/Development/git/EASyProducer/Plugins/Instantiation/de.uni_hildesheim.sse.vil.buildlang.tests/testdata/artifacts/lib/commons-io-2.4.jar!/' instead.</i><br>
These warnings are generated by <i>org.eclipse.emf.mwe.utils.StandaloneSetup</i> while registering mappings from Platform Plugin URIs to File or Platform Resource URIs (more information on that class, see <a href=http://download.eclipse.org/modeling/emft/mwe/javadoc/2.3/org/eclipse/emf/mwe/utils/StandaloneSetup.html>here</a>). More precisely, the warnings are thrown if an archive is already part of the known mappings (identified by the archive’s name) to avoid duplicates.<br>
However, debugging the usage of <i>org.eclipse.emf.mwe.utils.StandaloneSetup</i> while generating the languages showed that this mapping is never used: There is no single call to that class that asks for a created mapping. This is an obvious behaviour as this mapping is only used if the code is not running in an Eclipse/Equinox environment, which is not the case when generating the languages.<br>
<b>Conclusion:</b> The warnings during language generation can be ignored.
<br><br>
<b>Additional issue:</b>

<ul><li>change of interface <i>IXtextDocumentContentObserver</i> from Xtext version 2.5.3 to version 2.8.4 implemented by inner class <i>DocumentContextObserver</i> of class <i>de.uni_hildesheim.sse.dslcore.ui.editors.EmbeddedXtextSourceEditor</i></li></ul>

<b>Status: decision required</b><br>
<b>Explanation:</b>
The new version of interface <i>IXtextDocumentContentObserver</i> requires the implementation of method<br>
<i>public boolean hasPendingUpdates() {
    // TODO Auto-generated method stub
    return false;
}</i><br>
This method is not available in older Xtext versions.<br>
Further, the return type of the already implemented method<br>
<i>public void performNecessaryUpdates(Processor processor) {
}</i>
must now be <i>boolean</i>.<br>
<b>Conclusion:</b> The migration to Xtext version 2.8.4 results in a loss of backward-compatibility which will affect every user that is currently working with an older Xtext version.

**Comment by eichelbe** [comment]
Thanks for the overview. As we want to go for new Eclipse/xText versions, I would opt for increasing the version requirements in the using bundle manifests, realize the new methods, test it and commit it ;)
