### ISSUE TITLE
Eclipse workspace selection dialog disappears as soon as EASy is installed

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#30]
It seems that the check mark for ask for workspace at startup is disabled automatically... However, EASy is not modifying this. xText?

**Comment by eichelbe** [comment]
Based on Sascha's email... done? If not, potentially shift into next release.

**Comment by eichelbe** [comment]
@Elscha already done?

**Comment by Elscha** [comment]
It seems that this is a bug of **Eclipse and/or Xtext**. We get the same problem if we install Xtext without EASy. This can be solved by deleting the `configuration/.settings` folder within the Eclipse folder after installing Xtext (and also EASy), but we do not implemented any code, which should cause this error.
-> Unsolveable
