### ISSUE TITLE
EASy logo - keep, improve or redesign?

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#34]
Akin to other complex Eclipse-plugins, EASy shall show up in the Eclipse help after installation. 
Klaus: Discuss the recent logo...

**Comment by Elscha** [comment]
Meant was the "About Dialog" of Eclipse (Help -> About Eclipse). This is handled by the EASy-Producer.UI plugin via the icons/logo_icon.png. However, this will only be activated through the EASy-Producer Feature (definition of a branding plugin) and can only be tested within a EASy installation.
Currently, we use the same logo as used for the documentation and for the project page inside agilo:
![about](https://cloud.githubusercontent.com/assets/6489033/11091719/a75c3a98-887d-11e5-91ea-87535d3958e9.png)
![docu](https://cloud.githubusercontent.com/assets/6489033/11091721/ae8a86a8-887d-11e5-8ca8-a331750b4429.png)
![agilo](https://cloud.githubusercontent.com/assets/6489033/11091724/b57c651c-887d-11e5-8e17-5d22393b66ee.png)

**Comment by eichelbe** [comment]
Ok, technical side is already there. Then we reduce the topic to the logo discussion...

**Comment by eichelbe** [comment]
Decision was: keep
