### ISSUE TITLE
AssignmentResolver does not seem to consider AssignmentBlocks

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#37]
see confModel/FreezeTest

**Comment by eichelbe** [comment]
Background: As long as we use the assignment resolver for initializing the configuration rather than the reasoner, the assignment states of variables excluded by a but in a freeze block seem to be wrong as (it seems to me) the assigned annotation values are not taken over and the freeze evaluator cannot obtain a value. This causes failures in runtime reasoning and blocks further QM adaptation.

**Comment by eichelbe** [comment]
If possible, do not use the implementing constraints provided by the Assign class as we want to get rid of them (built dynamically in reasoning) - akin to typedef constraints.

**Comment by Elscha** [comment]
AssignmentResolver considers AssignmentBlocks since @0651f6be23c40ce33b3d4459b0fcb47017ac4b02 and @f21d7a4e0053ad4cbb00300bafa1d9ac6128e870
