### ISSUE TITLE
Reasoning of constraint variables

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#45]
Assigned/configured constraint variables do not work. See cases 1-3 attached. As this is blocking my work, I will commit a quick fix which solves my situation similar to 1 but not case 1.

Further, a simple if leads to a NPE (case 4)

[cases.zip](https://github.com/SSEHUB/EASyProducer/files/126789/cases.zip)

**Comment by rsizonenko** [comment]
Fixed. Test cases added.
Now true/false from the project are not filtered out for reasoning (filter changed).
Default values of ConstraintVariables are ignoring true/false as a constraint for evaluation.
Assigned values to the ConstraintVariables are not considered for evaluation (was like this)

**Comment by eichelbe** [comment]
Seems to solve case1-3. Anyway, the handling of false now is strange and just seems to be a workaround to me. If I write 
project P {
  false;
}
I would expect a failure message by the reasoner, but I might be the only one...
