### ISSUE TITLE
Error codes for reasoner

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#46]
Please add a numerical error code to the Message and define several error codes as constants, in particular to distinguish different cases of reasoning failures that can easily be handled by a program, e.g., logical constraint failure vs. arithmetic evaluation failure (div by 0). If this can then be used in the constraint analysis, and so (if we want) we can easily re-enable constraint failures in arithmetic evaluation rather than turning the evaluation into an undefined result as EASy does is since yesterday.

**Comment by rsizonenko** [comment]
Error codes in ReasoningErrorCodes (reasoning.core.reasoner). For now 2 types: failed reassignment and failed constraint. Message returns a list of all codes getErrorClassification().
Will be extended.

**Comment by eichelbe** [comment]
... also for constraint evaluation
