### ISSUE TITLE
Stop VIL/VTL execution

### ISSUE THREAD

**Issue by eichelbe** [SSEHUB/EASyProducer#53]
UI button to stop in case of accidental loops
Potential steps (instantiate)
- attach listener to stop button with actual executor when instantiation is triggered
- enable stop button
- disable instantiation button
- perform instantiation
  Potential steps (stop)
- call executor.stop()
- disable stop button
- enable instantiation button
  The same for rt-VIL (adaptation view), using the rt-VIL executor (extension of VIL executor)

**Comment by eichelbe** [comment]
@Elscha prereqisite #47 is committed...

**Comment by Elscha** [comment]
rt-VIL not considered
