### ISSUE TITLE
[EASyCommandLine] checkValidity: add option for configuring path to .result file

### ISSUE THREAD

**Issue by anb0s** [SSEHUB/EASyProducer#60]
.result file is created in project root, but in our case we do not want have generated files inside (may be readonly) project containers and have configured out-of-source-build folder where all generated files are created.

**Comment by anb0s** [comment]
I want to try the version 1.2.0 now. I've downloaded the EASyCommandLine.zip but it looks like the version from 2016...

**Comment by eichelbe** [comment]
Not much changed about the command line (demo), but the implementing parts. The Maven components can more easily be integrated into an own program as described in the developer guide. However, as the command line was not much in the focus, it you be that we missed to deploy it (there were not many requests for it). Could you please provide the URL, then we can check this out?

**Comment by anb0s** [comment]
Thanks, i was using the link described here: http://projects.sse.uni-hildesheim.de/easy/
Topic:
...
_EASy Command Line Tool
The EASy command line tool, which runs outside from Eclipse can be downloaded here._
...
http://projects.sse.uni-hildesheim.de/easy/EASyCommandLine.zip

**Comment by eichelbe** [comment]
Ah ok. It seems we missed updating this. I've updated this file as well as the release guide c7ef8dc6226811eb0782e34f7350d4e73215fc3f However, probably the issue is still open...

**Comment by anb0s** [comment]
OK, thanks. I will use the new version together with files created by new version 1.2.0 and report then.
