### ISSUE TITLE
[EASyCommandLine] checkValidity: accept passing <project_folder> only

### ISSUE THREAD

**Issue by anb0s** [SSEHUB/EASyProducer#61]
Like the command "easy instantiateSelf <project_folder>" the command "easy checkValidity <project_folder>" should be possible without passing the parameter "<absolute path to ivml_file>". 

Background: i want to check the validity and instantiate with same set of "meta" information about the project, e.g. want to store only the path to the project during headless (CI server) build.

**Comment by anb0s** [comment]
Thanks, how can i test it? is there a "nightly build" of command line tool too?

**Comment by Elscha** [comment]
You can download the current build from our ci server directly from: http://jenkins.sse.uni-hildesheim.de/job/Standalone/lastSuccessfulBuild/artifact/EASyCommandLine/build/EASyCommandLine.zip

Please check before, that the build is green (meaning that also the tests are running).

**Comment by anb0s** [comment]
Thanks, it works like expected :)
