### ISSUE TITLE
[SSE-Reasoner] Assignments may overwrite user defined values 

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#65]
Given the following scenario:

```
project PL_Freeze {

    version v0;
    compound CP1 {
        setOf(Integer) ints;
    }

    CP1 cmp1;
    cmp1 = {ints = {1, 2}};
}
```

The user "extends" the nested set `ints` by two more nested elements and configures them, e.g. with values 3 and 4. During reasoning the value of the compound will be "reseted" to `{ints = {1, 2}}` again. As a consequence, the UI will loose the value assignments for the newly created elements of the set.

This causes also trouble for the undo function while freezing the complete configuration, whicht triggers a reasoning before the freeze operation, to avoid freezing inconsitent configurations (cf. #64).
CC: @eichelbe

**Comment by eichelbe** [comment]
Seems to be gone with the new reasoner version.
