### ISSUE TITLE
Editor does not allow nested eval blocks

### ISSUE THREAD

**Issue by rsizonenko** [SSEHUB/EASyProducer#66]
Editor does not allow to model nested eval blocks (both in top-level project and in compounds)
Example:
compound C {
        Integer a;
        eval {
            a > 0;
            eval {
                a < 100;
            }
        }
    }

Editor complains: missing '}' at 'eval' and extraneous input '}' expecting EOF

**Comment by eichelbe** [comment]
Example is not correct, nested eval blocks must go first. Made grammar a bit more liberal to allow also plain nesting of eval blocks. Access to nested eval blocks happens via the contained elements - removed specific interface to keep the block similar to freeze.

Added test case...

**Comment by eichelbe** [comment]
Please check / close.

**Comment by rsizonenko** [comment]
Nested evals possible (also multiple ones) when the come in the beginning of current eval block - checked
