### ISSUE TITLE
[IVML-Parser]: Assignment of compound slots in not related compounds

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#69]
In a compound, which does not refine another compound, slots of the latter can be assigned. This will not show any errors.
For instance:

```
project faultyAssignment {

    version v0;

    compound CP1 {
      Integer no;
      Constraint cons = no > 0;
    }

    compound CP2 {
      cons = null;
    }

    CP2 cmp;
}
```

The assignment of cons in CP2 should not be possible.

**Comment by eichelbe** [comment]
Issue is confirmed...
