### ISSUE TITLE
IVML/VIL: Refined Compound Types in a Container are not considered

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#70]
A container of a compound (not reference to a compound) with explicit type initializers does not consider the correct types in VIL if an advice is used. For instance:
**IVML:**

```
project TypeTest {

    version v0;
    compound CP {
        String s1;
    }

    compound CP2 refines CP {
        String s2;
    }

    sequenceOf(CP) cmps = {{s1 = "hello"}, CP2 {s2 = "world", s1 = "hello"}};
    cmps = {{s1 = "hello"}, CP2 {s2 = "world", s1 = "hello"}};
    freeze {
        cmps;
    }
}

```

**VIL:**

```
@advice(TypeTest)
vilScript TypeTest (Project source, Configuration config, Project target) {

    version v0;

    main(Project source, Configuration config, Project target) = : {
      DecisionVariable v;
      TypeTest cfg = config;
      sequenceOf(CP) cs = cfg.cmps;
      sequenceOf(CP) filtered = cs->select(CP element | element.getType() == "CP2");

      map(CP cmp : cs) {
        println(cmp.getType());
      };
    }
}
```

Will print out CP two times and, thus, `filtered` will be empty. If the whole structure is changed to a 
`sequenceOf(`**`refTo`**`(CP))` scenario, the example will work as expected: Two different types will be printed and `filtered` will contain (only) the second element.

**Comment by eichelbe** [comment]
Caused by the confModel as not the specific types of the values are assigned upon creation.
