### ISSUE TITLE
IVML-Parser: Transparent handling of references does not work (parameters are not compliant)

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#72]
Collections operating on references and collections operating on the refered type are not compliant, e.g., situations like :

```
project IVML {

    version v0;
    sequenceOf(String) strs1;
    sequenceOf(refTo(String)) strs2;

    strs1 == strs2;
}
```

are rather hard to handle.

CC: @eichelbe

**Comment by eichelbe** [comment]
So far not defined by the IVML language specification, or?

**Comment by Elscha** [comment]
There is nothing defined for such situations. In some cases it works, in other not. As there is no clearly defined unpack function, I do not know how to make such collections compareable.

**Comment by eichelbe** [comment]
apply over individual elements does not help?

**Comment by Elscha** [comment]
This problem would be solveable if at least #74 would work. However, the handling would not be very pretty :confused:

**Comment by Elscha** [comment]
Also

```
project IVML {

    version v0;
    sequenceOf(String) strs1;
    sequenceOf(refTo(String)) strs2;

    strs2->apply(refTo(String) s, setOf(String) set = {} | set.add(s));
}
```

does not help.

**Comment by eichelbe** [comment]
why should this help, this is not a comparison

**Comment by Elscha** [comment]
OK, that seems to work:

```
project IVML {

    version v0;
    setOf(String) strs1;
    setOf(refTo(String)) strs2;

    strs1 = strs2->apply(refTo(String) s; setOf(String) set = {} | set.add(refBy(s)));
}
```

However, the  [IVML Language Specification](http://projects.sse.uni-hildesheim.de/easy/docs/ivml_spec.pdf#page=46) must be updated, as a comma is used to separate both parameter inside the apply instead of the semicolon

**Comment by eichelbe** [comment]
Fine. There shall be an updated description of apply, in particular for temporary declarators. Could you please check and, if require, update the spec?

**Comment by Elscha** [comment]
Yes, I will do that.

**Comment by Elscha** [comment]
Fixed the  IVML Language Specification. However, the reasoner does not consider such constraints.
In both models, the reasoner will detect no errors (only the second one should be valid):

```
project IVML {

    version v0;
    sequenceOf(String) array = {"Hello", " ", "World"};
    setOf(refTo(String)) referedVars = {refBy(array[0]), refBy(array[2])};
    setOf(String) orgVars;

    referedVars->apply(refTo(String) itr;
      setOf(String) tmpValues = {} | tmpValues.add(refBy(itr))).size() == 1;
}
```

```
project IVML {

    version v0;
    sequenceOf(String) array = {"Hello", " ", "World"};
    setOf(refTo(String)) referedVars = {refBy(array[0]), refBy(array[2])};
    setOf(String) orgVars;

    referedVars->apply(refTo(String) itr;
      setOf(String) tmpValues = {} | tmpValues.add(refBy(itr))).size() == 2;
}
```

Also in this case, no value will be assigned to `orgVars`, even if this may be ok as it is questionable wehther a permanent assignment should be poosible:

```
project IVML {

    version v0;
    sequenceOf(String) array = {"Hello", " ", "World"};
    setOf(refTo(String)) referedVars = {refBy(array[0]), refBy(array[2])};
    setOf(String) orgVars;


    // "Derefer" values
    orgVars = referedVars->apply(refTo(String) itr;
      setOf(String) tmpValues = {} | tmpValues.add(refBy(itr)));
}
```

**Comment by eichelbe** [comment]
Hi,

warum sollte in den ersten zwei Fällen was assigned werden - und was tut
der reasoner da? Beim dritten sollte was passieren, liegt ggf. aber am
EvaluationVisitor. Also sollten wir das erst mal prüfen. Kannst du aus
dem dritten einen Testcase machen?

Viele Grüße,
Holger

**Comment by Elscha** [comment]
Hallo Holger,

bei den ersten beiden Fällen erstelle ich mittels des applys eine temporäre Liste, deren Länge ich überprüfe. Nach meinem Verständnis sollte die Läge 2 sein, womit im ersten Fall ein Fehler gefunden werden müsste.
Ist für den dritten Fall tatsächlich das Assignment gewünscht (hatten wir ja gestern drüber gesprochen)? Dann kann ich den Testfall erstellen.

Mit freundlichen Grüßen
Sascha El-Sharkawy

**Comment by Elscha** [comment]
Found the failure in:
- [ContainerOperations:89](https://github.com/SSEHUB/EASyProducer/blob/1a213d0a8694f2186c05f2b8c5c6320c2a6584e8/Plugins/VarModel/Model/src/net/ssehub/easy/varModel/cstEvaluation/ContainerOperations.java#L89)
- [ContainerValue:473](https://github.com/SSEHUB/EASyProducer/blob/9ebd313ea1c410ae4de44b7a2810b346246d86b0/Plugins/VarModel/Model/src/net/ssehub/easy/varModel/model/values/ContainerValue.java#L473)

The error occurs if a reference value (for `aValue`) is added to a container, which is not operating on references. I'm not realy sure how to handle it without breaking something else.

**Comment by eichelbe** [comment]
**Original post:** IVML parser correctly complains about type inequality ("he types of all parameters of operation '==' need to be compliant"). IVML design having explicit type operations for references requires in this situation refBy(.). New version of IVML to be committed warns about potential comparison flaws for unequal types (inspired by this issue).

**Comment by eichelbe** [comment]
**Examples from 18 Jul 2016:** Actual version of IVML reasoner handles these situations as expected. Commit for respective test cases will follow.
