### ISSUE TITLE
IVML-Parser: Transparent handling of references does not work (in predefined functions)

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#74]
Operations for collections differ between collections based on references and collections based on the referred type. It becomes inpossible to _unpack_ a referred variable to facilitate a comparision as desired in #72. For instance, the example from below does not work for `str2`. Also ommiting `refBy` and `refTo` does not help:

```
project IVML {

    version v0;
    setOf(String) strs1;
    setOf(refTo(String)) strs2;

    setOf(String) set1 = strs1->collect(s | s);
    setOf(String) set2 = strs2->collect(refTo(String) s | refBy(s));
}
```

This was used as a workaround for #72 
CC: @eichelbe

**Comment by eichelbe** [comment]
Works with new version of reasoner/IVML object model. Regression test will follow.
