### ISSUE TITLE
Reasoner: Reasoner modifies data model during CHECK method

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#75]
Even if the reasoner is called via its `ReasonerFrontend.getInstance().check` method, it modifies the underlying project. Especially in [Resolver:672](https://github.com/SSEHUB/EASyProducer/blob/ca1bb919e2706d00ae84d5355dd6192617043706/Plugins/Reasoner/EASy-Original-Reasoner/de.uni_hildesheim.sse.reasoning.reasoner/src/net/ssehub/easy/reasoning/sseReasoner/Resolver.java#L672), the reasoner is exchanging general `Compound` constraints through constraints pointing to compound instances by using `CompoundAccess`.
Thus constraints are exchanged in the following manner during reasoning:
Before:
`inputTypes = source.input;`
After:
`PriorityPipCfg::PriorityPip_Source0.inputTypes = PriorityPipCfg::PriorityPip_Source0.source.input;`

I suggest the following solutions:
- During the `check` method, the reasoner may create a `Configuration`. This would solve some propagation problems in general, but not this kind of problem.
- Such constraints may be saved inside the Reasoner, but must not be stored in model elements.

CC: @eichelbe

**Comment by eichelbe** [comment]
Agree. In particular, during propagation, the reasoner is only allowed to change values, but not constraints or model structures!

**Comment by Elscha** [comment]
Propably, this happens only for `PartialEvaluationBlock`s in [Resolver:708](https://github.com/SSEHUB/EASyProducer/blob/ca1bb919e2706d00ae84d5355dd6192617043706/Plugins/Reasoner/EASy-Original-Reasoner/de.uni_hildesheim.sse.reasoning.reasoner/src/net/ssehub/easy/reasoning/sseReasoner/Resolver.java#L708).
In all other parts, constraints are already copied before modifying them.

**Comment by rsizonenko** [comment]
Should be resolved. Please check in QM.

**Comment by Elscha** [comment]
Thanks,  e275e0c78402ea6861fca35112480cc1348fce44 solves the issue (but unfortunately not my problem).
